CREATE TABLE IF NOT EXISTS TASK (
  TASK_ID     VARCHAR(255) PRIMARY KEY NOT NULL,
  USER_ID     VARCHAR(255),
  TIMESTAMP   TIMESTAMP,
  TITLE       VARCHAR(255),
  DESCRIPTION VARCHAR(255),
  DONE        BOOLEAN
);
